export interface Building {
  id: string;
  campusId: string;
  names: string[];
  shortNames: string[];
  address: string;
}

export const buildings: Building[] = [
  {
    id: "A-1",
    campusId: "PIOTROWO",
    names: ["Wydział Informatyki"],
    shortNames: ["A-1", "WI"],
    address: "",
  },
  {
    id: "A-1a",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-1a"],
    address: "",
  },
  {
    id: "A-2",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-2"],
    address: "",
  },
  {
    id: "A-3",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-3"],
    address: "",
  },
  {
    id: "A-4",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-4"],
    address: "",
  },
  {
    id: "A-5",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-5"],
    address: "",
  },
  {
    id: "A-6",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-6"],
    address: "",
  },
  {
    id: "A-7",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-7"],
    address: "",
  },
  {
    id: "A-8",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-8"],
    address: "",
  },
  {
    id: "A-9",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-9"],
    address: "",
  },
  {
    id: "A-10",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-10"],
    address: "",
  },
  {
    id: "A-11",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-11"],
    address: "",
  },
  {
    id: "A-12",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-12"],
    address: "",
  },
  {
    id: "A-13",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-13"],
    address: "",
  },
  {
    id: "A-14",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-14"],
    address: "",
  },
  {
    id: "A-15",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-15"],
    address: "",
  },
  {
    id: "A-16",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-16"],
    address: "",
  },
  {
    id: "A-17",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-17"],
    address: "",
  },
  {
    id: "A-18",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-18"],
    address: "",
  },
  {
    id: "A-19",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-19"],
    address: "",
  },
  {
    id: "A-20",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-20"],
    address: "",
  },
  {
    id: "A-21",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-21"],
    address: "",
  },
  {
    id: "A-22",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-22"],
    address: "",
  },
  {
    id: "A-23",
    campusId: "PIOTROWO",
    names: ["Centrum Wykładowe"],
    shortNames: ["A-23", "CW"],
    address: "",
  },
  {
    id: "A-23BT",
    campusId: "PIOTROWO",
    names: ["Biblioteka Techniczna"],
    shortNames: ["A-23", "BT"],
    address: "",
  },
  {
    id: "A-24",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-24"],
    address: "",
  },
  {
    id: "A-25",
    campusId: "PIOTROWO",
    names: [],
    shortNames: ["A-25"],
    address: "",
  },
];
